replicaCount: 2

image:
  repository: mass-calculator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9090
  nodePort: 30009

env:
  port: 9090

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  enabled: false
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []
